# Site settings
title: Hagaluganasu
author:
  name: Vivek Jadhav
  email: vivekjadhavsagar10 [at] gmail [dot] com
description: "Site on GH-Pages"

# Build settings
remote_theme: jekyll/minima

minima:
  social_links: 
    instagram: vivek_j19
    twitter: 19nanavanalla
     

  
