# Site settings
title: Hagaluganasu
author:
  name: Vivek Jadhav
  email: vivekjadhavsagar10 [at] gmail [dot] com
description: "Site on GH-Pages"

show_excerpts: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
    

# Build settings
remote_theme: jekyll/minima

minima:
  social_links: 
    instagram: vivek_j19
    facebook: https://www.facebook.com/vivek.jadhav.3382/
  
  header_pages:
    - about.md
   
     

  
