# Site settings
title: Hagaluganasu
author:
  name: Vivek Jadhav
  email: vivekjadhavsagar10@gmail.com
description: "Site on GH-Pages"

# Build settings
remote_theme: jekyll/minima

minima:
  social_links: 
    instagram: vivek_j19
  
    

  
