# Site settings
title: Hagaluganasu
author:
  name: Vivek Jadhav
  email: vivekjadhavsagar10 [at] gmail [dot] com
description: "Site on GH-Pages"

show_excerpts: true

# Build settings
remote_theme: jekyll/minima

minima:
  social_links: 
    instagram: vivek_j19
    twitter: 19nanavanalla
  
  header_pages:
    - about.md
    
plugins:
 - jekyll-feed
 - jekyll-seo-tag
    
     

  
