# Site settings
title: Hagaluganasu
subtitle: vivekj
author:
  name: Vivek Jadhav
  email: vivekjadhavsagar10@gmail.com
description: "Site on GH-Pages"

# Build settings
remote_theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "aqua"
  
