# Site settings
title: Hagaluganasu
subtitle: subtitle
author:
  name: Vivek Jadhav
  email: vivekjadhavsagar10 [at] gmail [dot] com
description: 

show_excerpts: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
    

# Build settings
remote_theme: jekyll/minima

minima:
  social_links: 
    instagram: vivek_j19
    facebook: vivekj19
  

     

  
